version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_svc
    ports:
      - "8080:80"
    environment:
      APP_SERVER_URL: ":80"
      CONFIG: "/etc/companysvc/conf"
    volumes:
      - "./config.yaml:/etc/companysvc/conf.yaml:ro"
    networks:
      - app
    depends_on:
      - postgres
      - nats
    restart: always

  postgres:
    container_name: postgres_svc
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "companies"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: always

  nats:
    container_name: queue_svc
    image: nats:2.8-alpine3.15
    restart: always
    networks:
      - app
    ports:
      - 4222:4222

  pgweb:
    container_name: pgweb_svc
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/companies?sslmode=disable"
    ports:
      - "6080:8081"
    networks:
      - app
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  postgres:
  pgadmin:
